USE [master]
GO
/****** Object:  Database [HocSinh]    Script Date: 6/23/2023 8:21:09 PM ******/
CREATE DATABASE [HocSinh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HocSinh', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.THUOCLE\MSSQL\DATA\HocSinh.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HocSinh_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.THUOCLE\MSSQL\DATA\HocSinh_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [HocSinh] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HocSinh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HocSinh] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HocSinh] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HocSinh] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HocSinh] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HocSinh] SET ARITHABORT OFF 
GO
ALTER DATABASE [HocSinh] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HocSinh] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HocSinh] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HocSinh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HocSinh] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HocSinh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HocSinh] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HocSinh] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HocSinh] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HocSinh] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HocSinh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HocSinh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HocSinh] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HocSinh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HocSinh] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HocSinh] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HocSinh] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HocSinh] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [HocSinh] SET  MULTI_USER 
GO
ALTER DATABASE [HocSinh] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HocSinh] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HocSinh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HocSinh] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [HocSinh] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HocSinh] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [HocSinh] SET QUERY_STORE = ON
GO
ALTER DATABASE [HocSinh] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [HocSinh]
GO
/****** Object:  Table [dbo].[HocSinh]    Script Date: 6/23/2023 8:21:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HocSinh](
	[HocsinhID] [int] IDENTITY(1,1) NOT NULL,
	[LopID] [int] NOT NULL,
	[Hoten] [nvarchar](50) NOT NULL,
	[Gioitinh] [nvarchar](5) NOT NULL,
	[Ngaysinh] [date] NOT NULL,
	[Diachi] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
 CONSTRAINT [PK_HocSinh] PRIMARY KEY CLUSTERED 
(
	[HocsinhID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Lop]    Script Date: 6/23/2023 8:21:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lop](
	[lopID] [int] IDENTITY(1,1) NOT NULL,
	[Tenlop] [nvarchar](5) NOT NULL,
	[Siso] [int] NOT NULL,
	[GVCN] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Lop] PRIMARY KEY CLUSTERED 
(
	[lopID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HocSinh]  WITH CHECK ADD  CONSTRAINT [FK_HocSinh_Lop] FOREIGN KEY([LopID])
REFERENCES [dbo].[Lop] ([lopID])
GO
ALTER TABLE [dbo].[HocSinh] CHECK CONSTRAINT [FK_HocSinh_Lop]
GO
USE [master]
GO
ALTER DATABASE [HocSinh] SET  READ_WRITE 
GO
